import {useEffect,useState} from 'react';
import {Eye,EyeOff,LockKeyhole,LoaderCircle,ArrowLeft,Check} from 'lucide-react';
type Status={authenticated:boolean;needsSetup:boolean;setupAvailable:boolean;recoveryAvailable:boolean;email?:string};
type Mode='login'|'setup'|'recover'|'password';
export default function Admin(){
 const [status,setStatus]=useState<Status|null>(null),[mode,setMode]=useState<Mode>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[setupKey,setSetupKey]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[show,setShow]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/admin');const j=await r.json() as Status & {error?:string};if(!r.ok)throw Error(j.error||'દુકાન સાથે જોડાણ થયું નથી.');setStatus(j);setEmail(j.email??'');if(j.authenticated){if(new URLSearchParams(location.search).get('mode')==='password')setMode('password');else location.replace('/?manage=1#collection');}else setMode(j.needsSetup?'setup':'login');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{document.documentElement.lang='gu';load();},[]);
 function switchMode(next:Mode){setMode(next);setError('');setPassword('');setConfirm('');setSetupKey('');setShow(false);}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode!=='login'&&password!==confirm){setError('બંને password એકસરખા રાખો.');return;}setBusy(true);try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email,password,setupKey,currentPassword,phone,address})});const j=await r.json() as Status & {error?:string};if(!r.ok)throw Error(j.error||'સાચવી શકાયું નથી.');location.replace('/?manage=1#collection');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const creating=mode==='setup',changing=mode==='password',recovering=mode==='recover';
 return <main className="login-page"><a href="/" className="login-brand">MAHI CREATION</a><section className={'login-card '+(creating?'setup-card':'')}><span className="login-emblem"><LockKeyhole size={25}/></span><p className="eyebrow">BOUTIQUE MANAGEMENT</p><h1>{creating?'તમારી દુકાન તૈયાર કરો':changing?'લોગિનની વિગતો બદલો':recovering?'નવો password બનાવો':'દુકાનનું લોગિન'}</h1><p>{creating?'એક વાર setup કરો. પછી અહીંથી પ્રોડક્ટ, ફોટા, ભાવ અને WhatsAppની વિગતો સંભાળો.':changing?'નવો password સાચવ્યા પછી બીજા ઉપકરણોમાં ફરી લોગિન કરવું પડશે.':'આ વિભાગ માત્ર દુકાનના માલિક માટે છે.'}</p>
 {loading?<div className="empty"><LoaderCircle className="spin"/><p>દુકાનની વિગતો તપાસી રહ્યા છીએ…</p></div>:!status?<><p className="error" role="alert">{error}</p><button className="primary" onClick={load}>ફરી પ્રયત્ન કરો</button></>:creating&&!status.setupAvailable?<div className="setup-help"><h2>પહેલાં એક સુરક્ષિત setup code રાખો</h2><p>Cloudflareમાં તમારી દુકાનના <strong>Settings → Variables and Secrets → Add</strong> ખોલો.</p><ol><li>Type: <strong>Secret</strong></li><li>Name: <code>ADMIN_PASSWORD</code></li><li>Value: તમારો પોતાનો લાંબો ગુપ્ત code</li></ol><p>Save / Deploy કરો. પછી નીચેનું બટન દબાવો. આ code ફક્ત માલિક જ દુકાનનું setup કરી શકે તે માટે છે.</p><button className="primary" onClick={load}>Code સેટ કર્યો છે · ફરી તપાસો</button></div>:<form onSubmit={submit}>
 {(creating||recovering)&&<label>માલિકનો {creating?'setup':'recovery'} code<input type="password" autoComplete="off" required maxLength={500} value={setupKey} onChange={e=>setSetupKey(e.target.value)}/><small>Hostingમાં Secret તરીકે રાખેલો ADMIN_PASSWORD.</small></label>}
 <label>લોગિન email<input type="email" autoComplete="username" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>
 {changing&&<label>હાલનો password<input type="password" autoComplete="current-password" required maxLength={500} value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label>}
 <label>{mode==='login'?'Password':'નવો password'}<div className="password-field"><input type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?'Password છુપાવો':'Password બતાવો'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div>{mode!=='login'&&<small>ઓછામાં ઓછા 12 અક્ષર રાખો.</small>}</label>
 {mode!=='login'&&<label>Password ફરી લખો<input type="password" autoComplete="new-password" required minLength={12} maxLength={200} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}
 {creating&&<><label>દુકાનનો WhatsApp નંબર<input type="tel" autoComplete="tel" required maxLength={20} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="10 અંકનો મોબાઇલ નંબર"/><small>ભારતનો 10 અંકનો નંબર આપો; 91 આપમેળે ઉમેરાશે.</small></label><label>દુકાનનું સરનામું · વૈકલ્પિક<textarea maxLength={500} value={address} onChange={e=>setAddress(e.target.value)}/></label></>}
 {error&&<p role="alert" className="error">{error}</p>}
 <button className="primary" disabled={busy} type="submit">{busy?<LoaderCircle className="spin" size={18}/>:mode==='login'?<LockKeyhole size={17}/>:<Check size={18}/>} {busy?'થોડી વાર…':creating?'દુકાન શરૂ કરો':mode==='login'?'લોગિન કરો':'સાચવો'}</button>
 {mode==='login'&&status.recoveryAvailable&&<button type="button" className="text-button" onClick={()=>switchMode('recover')}>Password ભૂલી ગયા?</button>}
 {(recovering||(creating&&!status.needsSetup))&&<button type="button" className="text-button" onClick={()=>switchMode('login')}>લોગિન પર પાછા જાઓ</button>}
 {mode==='login'&&status.setupAvailable&&<button type="button" className="text-button" onClick={()=>switchMode('setup')}>દુકાનનું setup પૂર્ણ કરો</button>}
 </form>}
 <a className="back-home" href={status?.authenticated?'/?manage=1#collection':'/'}><ArrowLeft size={15}/>{status?.authenticated?'દુકાન મેનેજ કરવા પાછા જાઓ':'કલેક્શન પર પાછા જાઓ'}</a></section></main>;
}
